INFO:pyaf.std:START_TRAINING 'signal'
Traceback (most recent call last):
  File "tests/basic_checks/issue_46_non_existant_time_column.py", line 8, in <module>
    lEngine.train(df , 'date_other' , 'signal', 1);
  File "/home/antoine/dev/python/packages/pyaf/ForecastEngine.py", line 25, in train
    self.mSignalDecomposition.train(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/antoine/dev/python/packages/pyaf/TS/SignalDecomposition.py", line 496, in train
    self.checkData(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/antoine/dev/python/packages/pyaf/TS/SignalDecomposition.py", line 463, in checkData
    raise Exception("TIME_COLUMN_NOT_FOUND " + str(iTime));
Exception: TIME_COLUMN_NOT_FOUND date_other
